server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST


db:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: root
      password:
      url: jdbc:mariadb://localhost/dbf_usage_db
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate.hbm2ddl.auto: create
        #hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
        hibernate.id.new_generator_mappings: false
      maxWaitForConnection: 60s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 32
      checkConnectionWhileIdle: true